modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/SilentChaos512/Silent-Gear/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/silent-gear"
logoFile="logo.png"
#credits="Thanks for this example mod goes to Java"
authors="SilentChaos512"

[[mods]]
    modId="silentgear"
    version="${file.jarVersion}"
    displayName="Silent Gear"
    updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/Silent-Gear/1.18.x/update.json"
    description='''
    Modular and upgradeable tools, weapons, and armor. Allows full customization of materials and parts used in gear crafting, even user-defined ones!
    '''

[[dependencies.silentgear]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.18,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.silentgear]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.silentgear]]
    modId="silentlib"
    mandatory=true
    versionRange="[6.2,7)"
    ordering="NONE"
    side="BOTH"
